spring:
  # Database Configuration
  datasource:
    url: ${DEPOSIT_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers:
      - ${KAFKA_1_CONTAINER_NAME}:9090
    consumer:
      group-id: order-service
      properties:
        allow.auto.create.topics: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus   # 노출할 엔드포인트
        exclude: beans, env, mappings                # 노출하지 않을 엔드포인트
      base-path: /actuator                            # 엔드포인트 기본 경로
  endpoint:
    health:
      show-details: always                           # 헬스체크 상세 정보
    info:
      enabled: true

custom:
  kafka:
    topic:
      user-create-event: ${KAFKA_USER_CREATE_TOPIC}
      user-create-event.dlq: ${KAFKA_USER_CREATE_DLQ_TOPIC}
      deposit-charge-event: ${KAFKA_DEPOSIT_CHARGE_TOPIC}
      deposit-charge-event.dlq: ${KAFKA_DEPOSIT_CHARGE_DLQ_TOPIC}
      order-event: ${KAFKA_ORDER_TOPIC}
      order-event.dlq: ${KAFKA_ORDER_DLQ_TOPIC}
      settlement-event: ${KAFKA_SETTLEMENT_TOPIC}
      settlement-event.dlq: ${KAFKA_SETTLEMENT_DLQ_TOPIC}
      refund-event: ${KAFKA_REFUND_TOPIC}
      refund-event.dlq: ${KAFKA_REFUND_DLQ_TOPIC}
      inventory-event: ${KAFKA_INVENTORY_TOPIC}
      inventory-event.dlq: ${KAFKA_INVENTORY_DLQ_TOPIC}