global:
  scrape_interval: 15s  # 15초마다 메트릭 수집

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8000']

  - job_name: 'auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth:8080']

  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user:8080']

  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order:8080']

  - job_name: 'deposit'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['deposit:8080']

  - job_name: 'payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment:8080']

  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product:8080']
