apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-dpy-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-dev
  template:
    metadata:
      labels:
        app: prometheus-dev
    spec:
      containers:
        - name: prometheus-pod-dev
          image: prom/prometheus:v2.45.0 # 안정적인 버전 사용 권장
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        # ConfigMap을 마운트하여 설정 파일을 사용합니다.
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config-dev
        # Prometheus 데이터 저장을 위한 임시 볼륨입니다. (운영 환경에서는 PVC 사용)
        - name: prometheus-data
          emptyDir: {}