apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc-dev
spec:
  type: ClusterIP
  selector:
    app: prometheus-dev
  ports:
    - port: 9090 # Prometheus의 웹 UI 및 API 포트
      targetPort: 9090
      protocol: TCP
      name: http