apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin-config-dev
data:
  # Zipkin의 기본 포트 설정 (deployment에 이미 정의되어 있어 필수 아님)
  # SPRING_APPLICATION_JSON: '{"server":{"port":9411}}'

  # Trace 데이터 최대 보관 기간 설정 (예시)
  # STORAGE_TYPE이 'memory'일 때만 적용됩니다.
  ZIPKIN_STORAGE_STRICT_TRACE_ID: "false" # 예시 설정