spring:
  datasource:
    url: ${ORDER_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers:
      - ${KAFKA_1_CONTAINER_NAME}:9090

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus   # 노출할 엔드포인트
        exclude: beans, env, mappings                # 노출하지 않을 엔드포인트
      base-path: /actuator                            # 엔드포인트 기본 경로
  endpoint:
    health:
      show-details: always                           # 헬스체크 상세 정보
    info:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}

# External Service URLs
external:
  user-service:
    url: http://user-module:8080
  product-service:
    url: http://product-module:8080
  cart-service:
    url: http://cart-module:8080
  payment-service:
    url: http://order-module:8080
