spring:
  datasource:
    url: ${ORDER_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers:
      - http://kafka-svc-dev.dev.svc.cluster.local:9090



# External Service URLs
external:
  user-service:
    url: http://auth-svc-dev.dev.svc.cluster.local:8084
  product-service:
    url: http://product-svc-dev.dev.svc.cluster.local:8085
#  cart-service:
#    url: http://cart:8089
  payment-service:
    url: http://payment-svc-dev.dev.svc.cluster.local:8087

  # Payment Configuration
payment:
  widgetClientKey: ${PAYMENT_WIDGET_CLIENT_KEY}
  successUrl: http://localhost/api/orders/payment/success
  failUrl: http://localhost/api/orders/payment/fail
logging:
  level:
    root: info
