# 도커 컨테이너 내부에서 실행될 때 사용

spring:
  # MySQL 데이터베이스 설정
  datasource:
    url: jdbc:mysql://product-db:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: gooream
    password: gooream1234!@

  # Elasticsearch 설정
  elasticsearch:
    uris: http://elasticsearch-1:9200

api:
  user:
    base-url: http://user-module:8080