spring:
  # MySQL 데이터베이스 설정
  # 로컬에서는 3306으로 사용하셔야 할 것 같습니다. 아마 호남님이 안켜졌던 문제가 각자 로컬에서 3306을 쓰는데 3311로 접속하려고 해서 그런것 아닌가 싶습니다.
  datasource:
#    url: jdbc:mysql://localhost:3311/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER_PRODUCT}
    password: ${DB_PASSWORD_PRODUCT}

  # JPA 설정
  jpa:
    hibernate:
      # 개발 환경
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Elasticsearch 설정
  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: product-service
      properties:
        allow.auto.create.topics: false

# 로깅 설정
logging:
  level:
    com.ll.products.domain.search: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: DEBUG

eureka:
  client:
    enabled: false

#현재 user 포트 8083번이라 일단 수정해놓았는데 이부분 이상있으시면 알려주세요
api:
  user:
    base-url: http://localhost:8083
#    base-url: http://localhost:8080