spring:
  # MySQL 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3311/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: gooream
    password: gooream1234!@

  # JPA 설정
  jpa:
    hibernate:
      # 개발 환경
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Elasticsearch 설정
  elasticsearch:
    uris: http://localhost:9202

  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: product-service
      properties:
        allow.auto.create.topics: false

api:
  user:
    base-url: http://localhost:8083