# 도커 컨테이너 내부에서 실행될 때 사용

spring:
  # MySQL 데이터베이스 설정
  datasource:
#    url: jdbc:mysql://product-db:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#    username: gooream
#    password: gooream1234!@
    url: ${PRODUCT_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  # Elasticsearch 설정
  elasticsearch:
    uris: http://elasticsearch-1:9200

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus   # 노출할 엔드포인트
        exclude: beans, env, mappings                # 노출하지 않을 엔드포인트
      base-path: /actuator                            # 엔드포인트 기본 경로
  endpoint:
    health:
      show-details: always                           # 헬스체크 상세 정보
    info:
      enabled: true




api:
  user:
    base-url: http://user-module:8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}
