# 도커 컨테이너 내부에서 실행될 때 사용
spring:
  # MySQL 데이터베이스 설정
  datasource:
    url: ${PRODUCT_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  # Elasticsearch 설정
  elasticsearch:
    uris: http://els-svc-dev.dev.svc.cluster.local:9200

  kafka:
    bootstrap-servers:
      - http://kafka-svc-dev.dev.svc.cluster.local:9090
    consumer:
      group-id: product-service
      properties:
        allow.auto.create.topics: false



api:
  user:
    base-url: http://auth-svc-dev.dev.svc.cluster.local:8084


logging:
  level:
    root: info

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      base-url: https://${AWS_S3_BUCKET}.s3.${AWS_REGION:ap-northeast-2}.amazonaws.com
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false