spring:
  application:
    name: products

  # 개발 환경 (운영에서는 prod로 변경)
  profiles:
    active: local

  # MySQL 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/products?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: Root123456!

  # JPA 설정
  jpa:
    hibernate:
      # 개발 환경
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Elasticsearch 설정
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s

  # JPA 설정 (데이터베이스와 Elasticsearch를 함께 사용)
  data:
    elasticsearch:
      repositories:
        enabled: true

# 로깅 설정
logging:
  level:
    com.ll.products.domain.search: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: DEBUG

api:
  user:
    base-url: http://localhost:8080