apiVersion: v1

kind: ConfigMap

metadata:
  name: kafka-config-dev

data:
  KAFKA_NODE_ID: "1"
  KAFKA_LISTENERS: "PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-svc-dev:9090,EXTERNAL://localhost:9092"
  #     common
  CLUSTER_ID: "QszDYpiURRaeCz86lsxokg"
  KAFKA_PROCESS_ROLES: "controller,broker"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9091"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  #     extra
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
  KAFKA_MIN_INSYNC_REPLICAS: "1"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "3000"
  TZ: "Asia/Seoul"
