apiVersion: v1

kind: ConfigMap

metadata:
  name: kafka-init-config-dev

data:
  init-topics.sh: |
    #!/usr/bin/env bash
    source "$(dirname "$0")/00-env.sh"
    
    echo "Initializing Kafka topics..."
    
    for TOPIC in "${!DEFAULT_TOPICS[@]}"; do
    PARTITIONS=${DEFAULT_TOPICS[$TOPIC]}
    log "Creating topic '$TOPIC' with $PARTITIONS partitions and $DEFAULT_REPLICATION replication"
    $KAFKA_BIN/kafka-topics.sh \
    --bootstrap-server "$BROKER" \
    --create \
    --topic "$TOPIC" \
    --partitions "$PARTITIONS" \
    --replication-factor "$DEFAULT_REPLICATION" \
    --if-not-exists \
    | tee -a "$LOG_DIR/topic.log"
    done
    
    echo "Kafka topics initialization completed."
    echo $KAFKA_BIN/kafka-topics.sh --list --bootstrap-server "$BROKER"
  00-env.sh: |
    #!/usr/bin/env bash
  
    # Kafka 기본 환경 변수
  
    # 브로커 노드 리스트 ( 현재 단일 노드 환경이므로 주석 처리 )
    BROKER="kafka-svc-dev:9090"
    #BROKER="kafka-1:9090,kafka-2:9090,kafka-3:9090"
    
    # 컨테이너 내부 Kafka CLI binary 위치
    KAFKA_BIN="/opt/kafka/bin"
    
    # Kafka 스크립트 로깅 경로
    LOG_DIR="/scripts/logs"
    mkdir -p $LOG_DIR
    
    # 기본 replication / partition 값
    # 현재 단일 노드 환경이므로 1로 설정
    DEFAULT_PARTITIONS=1
    DEFAULT_REPLICATION=1
    #DEFAULT_PARTITIONS=3
    #DEFAULT_REPLICATION=3
    
    # 기본 생성 Topic
    declare -A DEFAULT_TOPICS=(
    ["user-create-event"]=1
    ["user-create-event.dlq"]=1
    ["deposit-charge-event"]=1
    ["deposit-charge-event.dlq"]=1
    ["order-event"]=1
    ["order-event.dlq"]=1
    ["settlement-event"]=1
    ["settlement-event.dlq"]=1
    ["refund-event"]=1
    ["refund-event.dlq"]=1
    ["inventory-event"]=1
    ["inventory-event.dlq"]=1
    )
    
    # 시간 포맷
    NOW=$(date '+%Y-%m-%d %H:%M:%S')
    
    # 로그 출력 함수
    log() {
    echo "[$NOW] $1"
    }
  topic-handler.sh: |
    #!/usr/bin/env bash
    source "$(dirname "$0")/00-env.sh"

    usage() {
      echo "Usage:"
      echo "  $0 create <topic> [partitions] [replication] defaults to $DEFAULT_PARTITIONS partitions and $DEFAULT_REPLICATION replication"
      echo "  $0 delete <topic>"
      echo "  $0 describe <topic>"
      echo "  $0 list"
      echo "  $0 expand <topic> <new_partition_count>"
    }

    ACTION=$1
    TOPIC=$2
    PARTITIONS=${3:-$DEFAULT_PARTITIONS}
    REPLICATION=${3:-$DEFAULT_REPLICATION}

    case "$ACTION" in
      create)
        log "Creating topic '$TOPIC' ($PARTITIONS partitions, $REPLICATION replicas)"
        $KAFKA_BIN/kafka-topics.sh \
          --bootstrap-server "$BROKER" \
          --create \
          --topic "$TOPIC" \
          --partitions "$PARTITIONS" \
          --replication-factor "$REPLICATION" \
          --if-not-exists \
          | tee -a "$LOG_DIR/topic.log"
        ;;
      delete)
        log "Deleting topic '$TOPIC'"
        $KAFKA_BIN/kafka-topics.sh \
          --bootstrap-server "$BROKER" \
          --delete \
          --topic "$TOPIC" \
          | tee -a "$LOG_DIR/topic.log"
        ;;
      describe)
        log "Describing topic '$TOPIC'"
        $KAFKA_BIN/kafka-topics.sh \
          --bootstrap-server "$BROKER" \
          --describe \
          --topic "$TOPIC" \
        ;;
      list)
        log "Listing all topics"
        $KAFKA_BIN/kafka-topics.sh --list --bootstrap-server "$BROKER"
        ;;
      expand)
        NEW_PARTITION_COUNT=$3
        log "Expanding topic '$TOPIC' to $NEW_PARTITION_COUNT partitions"
        $KAFKA_BIN/kafka-topics.sh \
          --bootstrap-server "$BROKER" \
          --alter \
          --topic "$TOPIC" \
          --partitions "$NEW_PARTITION_COUNT"\
          | tee -a "$LOG_DIR/topic.log"
        ;;
      *)
        usage
        exit 1
        ;;
    esac