services:
  #kafka <--
  kafka-1:
    image: apache/kafka
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://localhost:9092
      #     common
      - CLUSTER_ID=QszDYpiURRaeCz86lsxokg
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      #     extra
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=3000
      - TZ=Asia/Seoul

    volumes:
      - ./scripts:/scripts
      - ./kafka-data-1:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9090 --list" ]
      interval: 5s
      retries: 10

  kafka-init:
    image: apache/kafka
    container_name: kafka-init
    depends_on:
      kafka-1:
        condition: service_healthy
    volumes:
      - ../infra/scripts:/scripts
    entrypoint: ["/bin/bash", "-c", "/scripts/init-topics.sh"]
    restart: "no"
