apiVersion: apps/v1
kind: Deployment
#이 파일 정의
metadata:
  name: payment-dpy-dev
#동작 정의
spec:
  replicas: 1
#  제어할 라벨
  selector:
    matchLabels:
      app: payment-dev
#      pod 정의
  template:
    metadata:
      labels:
        app: payment-dev
#        컨테이너 정의
    spec:
      containers:
        - name: payment-pod-dev
          image: payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: payment-config-dev
            - secretRef:
                name: payment-secret-dev
#            - secretRef:
#                name: payment-secret-key-dev
      restartPolicy: Always
