apiVersion: v1
kind: Service
metadata:
  name: grafana-svc-dev
spec:
  # 외부 접근을 위해 NodePort 타입으로 설정
  type: NodePort
  selector:
    app: grafana-dev
  ports:
    - port: 3000
      targetPort: 3000
      # 노출할 NodePort 번호 (Optional)
      nodePort: 30888
      protocol: TCP
      name: http-grafana