server:
  port: 0

spring:
  application:
    name: settlement

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql

  # Database Configuration
  datasource:
    url: jdbc:h2:mem:settlement-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: settlement-service
      properties:
        allow.auto.create.topics: false


custom:
  batch:
    chunk:
      size: 500

  kafka:
    topic:
      user-create-event: ${KAFKA_USER_CREATE_TOPIC}
      user-create-event.dlq: ${KAFKA_USER_CREATE_DLQ_TOPIC}
      deposit-charge-event: ${KAFKA_DEPOSIT_CHARGE_TOPIC}
      deposit-charge-event.dlq: ${KAFKA_DEPOSIT_CHARGE_DLQ_TOPIC}
      order-event: ${KAFKA_ORDER_TOPIC}
      order-event.dlq: ${KAFKA_ORDER_DLQ_TOPIC}
      settlement-event: ${KAFKA_SETTLEMENT_TOPIC}
      settlement-event.dlq: ${KAFKA_SETTLEMENT_DLQ_TOPIC}
      refund-event: ${KAFKA_REFUND_TOPIC}
      refund-event.dlq: ${KAFKA_REFUND_DLQ_TOPIC}
      inventory-event: ${KAFKA_INVENTORY_TOPIC}
      inventory-event.dlq: ${KAFKA_INVENTORY_DLQ_TOPIC}