spring:
  # Database Configuration
  datasource:
    url: ${CART_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}


  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  kafka:
    bootstrap-servers:
      - ${KAFKA_1_CONTAINER_NAME}:9090
    consumer:
      group-id: cart-service
      properties:
        allow.auto.create.topics: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}
# External Service URLs
external:
  user-service:
    url: http://user:8083

logging:
  level:
    root: info
