apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db-dpy-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db-dev
  template:
    metadata:
      labels:
        app: auth-db-dev
    spec:
      containers:
        - name: auth-db-pod-dev
          image: mysql:8.2.0
          envFrom:
#            - configMapRef:
#                name: auth-db-config-dev
            - secretRef:
                name: auth-db-secret-dev
          ports:
            - containerPort: 3308
          volumeMounts:
            - name: auth-db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: auth-db-data
          emptyDir: {}   # 개발용, 나중에 PVC로 변경 가능