apiVersion: v1
kind: Service
metadata:
  name: auth-svc-dev
spec:
  type: NodePort
  selector:
    app: auth-dev
  ports:
    - protocol: TCP
      port: 8084       # 내부 서비스 포트
      targetPort: 8084 # 컨테이너 포트
